SELECT CAR_ID, ROUND(AVG(DATEDIFF(DATE_ADD(END_DATE, INTERVAL 1 DAY), START_DATE)), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(DATE_ADD(END_DATE, INTERVAL 1 DAY), START_DATE)), 1)>=7
ORDER BY ROUND(AVG(DATEDIFF(DATE_ADD(END_DATE, INTERVAL 1 DAY), START_DATE)), 1) DESC, CAR_ID DESC;