SELECT SUM(SCORE) AS SCORE, B.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM  HR_DEPARTMENT AS A, HR_EMPLOYEES AS B, HR_GRADE AS C
WHERE A.DEPT_ID=B.DEPT_ID AND B.EMP_NO=C.EMP_NO AND YEAR=2022
GROUP BY B.EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1;
